repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--line-length=80]
  - repo: https://github.com/PyCQA/flake8
    rev: "7.2.0"
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    - id: pyupgrade
      args: [--py36-plus]
